### ISSUE TITLE
style: header

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/.github#4]
@brunny-eth I think the header here takes up a lot of space to me. Maybe there is a way to consolidate it somewhat to make it smaller?

**Comment by brunny-eth** [comment]
are you talking about the logo / brand name / little github sticker thingys? @Autoparallel recommended that we make it a little more colorful

i think it looks fine but if you have a specific suggestion i'm happy to try to implement it

**Comment by 0xJepsen** [comment]
I like to color actually what i mean is that the size + indentation is really big. IF we can reduce the whitespace before the first header that would be good. Maybe a good way to do would be to move the logo to the left of the Pluto text so that it's not on top of each other but next to each-other which would be a better utilization of space. Does that make sense?

**Comment by brunny-eth** [comment]
Issue resolved with [PR 6](https://github.com/pluto/.github/pull/6)
